### ISSUE TITLE
How do you debug in an IDE?

### ISSUE THREAD

**Issue by samuelkdavis-mccarthyfinch** [OfficeDev/Word-Add-in-GettingStartedFabricReact#2]
Visual Studio has a template for a Word web add-in. Clicking 'Start' opens Word with the add-in loaded, and allows for immediate debugging of the front-end javascript in the IDE.

![image](https://user-images.githubusercontent.com/41707320/61331016-19dc0380-a875-11e9-97c5-aa659276e002.png)

Word was running the add-in in ie11.

With this project, the only options I've found are debugging with 'f12' debugger located in C:\Windows\SysWOW64\F12\IEChooser.exe (or System32).

![image](https://user-images.githubusercontent.com/41707320/61331092-5871be00-a875-11e9-9663-a13ae9268e02.png)

I installed the latest version of windows to get access to the new Windows Terminal. This update also switched the Word add-in to load in edge instead of ie11, which requires the new Microsoft Edge Developer Tools.

![image](https://user-images.githubusercontent.com/41707320/61331217-9ff84a00-a875-11e9-9183-0e57d1a56a14.png)

I would like to get access to the functionality Visual Studio provides for debugging front-end code via an IDE instead of f12/edge developer tools. I cannot find out how Visual Studio allows this debugging as all of the properties are hidden away as settings in .sln and web.config etc.

Is there any way to debug this add-in with Visual Studio/vscode (preferrably vscode)?

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
